INSERT INTO servico (nome, descricao, duracao_estimada, preco, ativo) VALUES
('Corte Social', 'Corte tradicional masculino com tesoura e máquina', 30, 45.00, true),
('Corte Degradê', 'Corte com transição gradual de comprimento', 40, 55.00, true),
('Corte Militar', 'Corte curto e uniforme', 25, 35.00, true),
('Corte Infantil', 'Corte especial para crianças com técnicas lúdicas', 35, 40.00, true),
('Corte Pompadour', 'Estilo clássico com volume na frente', 45, 65.00, true),
('Corte Undercut', 'Lados raspados com topo mais longo', 40, 60.00, true),
('Corte Moicano', 'Estilo ousado com faixa central elevada', 50, 70.00, true),
('Corte Afro', 'Manutenção de cabelos crespos e cacheados', 45, 60.00, true),
('Barba Completa', 'Aparação e modelagem completa da barba', 30, 40.00, true),
('Barba com Navalha', 'Aparação com navalha tradicional', 35, 45.00, true),
('Sobrancelha', 'Design e manutenção de sobrancelhas', 15, 20.00, true),
('Pé de Cabelo', 'Acerto nas laterais e nuca', 20, 25.00, true),
('Hidratação Capilar', 'Tratamento para revitalização dos fios', 40, 80.00, true),
('Progressiva', 'Alisamento com formolização', 90, 150.00, true),
('Coloração', 'Tingimento dos fios', 60, 100.00, true),
('Luzes', 'Mechas para efeito de iluminação', 75, 120.00, true),
('Massagem Capilar', 'Massagem relaxante no couro cabeludo', 20, 30.00, true),
('Pacote Corte + Barba', 'Corte completo mais barba', 60, 85.00, true),
('Pacote Completo', 'Corte, barba e hidratação', 90, 140.00, true),
('Relaxamento', 'Tratamento para alinhamento dos fios', 60, 110.00, true);